// Code Generated by Sidekick is for learning and experimentation purposes only.
// Configuration for GitHub Pages Deployment
const GITHUB_PAGES_URL = "https://russellott.github.io/demosmartapp";

const FHIR_SERVERS = {
    // SMART Health IT Sandbox
    sandbox: {
        name: "SMART Health IT Sandbox",
        clientId: "123456",
        clientSecret: null,
        scope: "launch/patient patient/*.read openid fhirUser offline_access",
        redirectUri: `${GITHUB_PAGES_URL}/app.html`,
        launchUri: `${GITHUB_PAGES_URL}/launch.html`,
        iss: "https://launch.smarthealthit.org/v/r4/sim/WzMsIiIsIiIsIkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMSwiIl0/fhir",
        description: "Public testing sandbox with sample patients (R4, AUTO simulation)"
    },
    
    // Cigna FHIR Server
    cigna: {
        name: "Cigna Developer API",
        clientId: "9ffe6e94-9a21-473d-8e7b-759b4c431b13",
        clientSecret: "706170b4-3f2f-464f-8acd-6b1eeb84aa7c",
        // UPDATED: Added offline_access scope for refresh token
        scope: "patient/*.read launch/patient openid fhirUser offline_access",
        redirectUri: `${GITHUB_PAGES_URL}/app.html`,
        launchUri: `${GITHUB_PAGES_URL}/launch.html`,
        iss: "https://fhir.cigna.com/PatientAccess/v1-devportal",
        authorizeUrl: "https://r-hi2.cigna.com/mga/sps/oauth/oauth20/authorize",
        tokenUrl: "https://r-hi2.cigna.com/mga/sps/oauth/oauth20/token",
        description: "Real payer FHIR API for CMS Patient Access",
        requiresStateNonce: true,
        useNumericStateNonce: true
    },
    
    // Anthem FHIR Server
    anthem: {
        name: "Anthem FHIR API",
        clientId: "YOUR_ANTHEM_CLIENT_ID",
        clientSecret: "YOUR_ANTHEM_CLIENT_SECRET",
        scope: "patient/*.read launch/patient openid fhirUser offline_access",
        redirectUri: `${GITHUB_PAGES_URL}/app.html`,
        launchUri: `${GITHUB_PAGES_URL}/launch.html`,
        iss: "https://fhir.anthem.com/fhir",
        description: "Anthem's CMS-compliant Patient Access API"
    },
    
    // Logica Health Sandbox
    logica: {
        name: "Logica Health Sandbox",
        clientId: "YOUR_LOGICA_CLIENT_ID",
        clientSecret: null,
        scope: "launch/patient patient/*.read openid fhirUser offline_access",
        redirectUri: `${GITHUB_PAGES_URL}/app.html`,
        launchUri: `${GITHUB_PAGES_URL}/launch.html`,
        iss: "https://api.logicahealth.org/FHIRResearchSandbox/open/",
        description: "Advanced testing sandbox with rich test data"
    }
};

// Set which server to use by default
const ACTIVE_SERVER = 'cigna';

// Helper function to generate numeric state/nonce
function generateNumericToken(length = 10) {
    let result = '';
    for (let i = 0; i < length; i++) {
        result += Math.floor(Math.random() * 10);
    }
    return result;
}

// Helper function to get current configuration
function getCurrentConfig() {
    return FHIR_SERVERS[ACTIVE_SERVER];
}

// Helper to check if server is configured
function isServerConfigured(serverKey) {
    const server = FHIR_SERVERS[serverKey];
    if (!server || !server.clientId) return false;
    
    const placeholders = [
        'YOUR_CLIENT_ID',
        'YOUR_' + serverKey.toUpperCase() + '_CLIENT_ID',
        'YOUR_SANDBOX_CLIENT_ID'
    ];
    
    return !placeholders.some(p => server.clientId.includes(p));
}
