// Code Generated by Sidekick is for learning and experimentation purposes only.
/**
 * Custom token exchange handler for FHIR servers that need special handling
 * This is necessary because some servers (like Cigna) have specific requirements
 * for how the token request must be formatted
 */

// Override FHIR client's token exchange for specific servers
const TokenHandler = {

    toBase64(str) {
        try {
            return btoa(str);
        } catch (e) {
            return btoa(unescape(encodeURIComponent(str)));
        }
    },

    async executeTokenRequest(tokenUrl, bodyString, headers) {
        return fetch(tokenUrl, {
            method: 'POST',
            headers,
            body: bodyString,
            referrerPolicy: 'no-referrer'
        });
    },

    /**
     * Perform custom token exchange with explicit body formatting
     */
    async exchangeToken(tokenUrl, params) {
        console.log('=== Custom Token Exchange ===');
        console.log('Token URL:', tokenUrl);
        console.log('Parameters:', {
            ...params,
            client_secret: params.client_secret ? '***HIDDEN***' : 'not provided',
            code_verifier: params.code_verifier ? '***PROVIDED***' : 'not provided'
        });

        const tokenAuthMethod = params.token_auth_method || (params.code_verifier ? 'none' : 'client_secret_post');
        console.log('Token auth method:', tokenAuthMethod);
        if (params.server_key) {
            console.log('Server key:', params.server_key);
        }

        // Build the request body exactly as Cigna expects
        const body = new URLSearchParams();
        body.append('grant_type', params.grant_type || 'authorization_code');
        body.append('code', params.code);
        body.append('redirect_uri', params.redirect_uri);
        body.append('client_id', params.client_id);

        // client_secret_post: include secret in request body
        if (tokenAuthMethod === 'client_secret_post' && params.client_secret) {
            body.append('client_secret', params.client_secret);
            console.log('✓ client_secret added to request body');
        }

        // PKCE: Add code_verifier when using public-client auth
        if (params.code_verifier) {
            body.append('code_verifier', params.code_verifier);
            console.log('✓ code_verifier added to request body for PKCE flow');
        }

        if (!params.client_secret && !params.code_verifier) {
            console.warn('⚠ Neither client_secret nor code_verifier provided - token exchange may fail');
        }

        // Log the exact body that will be sent
        const bodyString = body.toString();
        console.log('Request body (form-urlencoded):', bodyString);

        // Log each parameter
        console.log('Body parameters:');
        for (const [key, value] of body.entries()) {
            if (key === 'client_secret') {
                console.log(`  ${key}: ***HIDDEN*** (length: ${value.length})`);
            } else if (key === 'code_verifier') {
                console.log(`  ${key}: ***PROVIDED*** (length: ${value.length})`);
            } else {
                console.log(`  ${key}: ${value}`);
            }
        }

        try {
            const headers = {
                'Content-Type': 'application/x-www-form-urlencoded'
            };

            if (tokenAuthMethod === 'client_secret_basic' && params.client_secret) {
                const basic = this.toBase64(`${params.client_id}:${params.client_secret}`);
                headers['Authorization'] = `Basic ${basic}`;
                console.log('✓ Using client_secret_basic Authorization header');
            }

            let response = await this.executeTokenRequest(tokenUrl, bodyString, headers);

            console.log('Response status:', response.status);
            console.log('Response headers:', Object.fromEntries(response.headers.entries()));

            if (!response.ok) {
                const errorText = await response.text();
                console.error('Token exchange failed:', {
                    status: response.status,
                    statusText: response.statusText,
                    body: errorText
                });

                let errorData;
                try {
                    errorData = JSON.parse(errorText);
                } catch (e) {
                    errorData = { error: 'parse_error', error_description: errorText };
                }

                if (
                    response.status === 400 &&
                    (errorData.error === 'invalid_client' || `${errorData.error_description || ''}`.toLowerCase().includes('client')) &&
                    params.client_secret
                ) {
                    const fallbackMethod = tokenAuthMethod === 'client_secret_basic' ? 'client_secret_post' : 'client_secret_basic';
                    console.warn(`⚠ invalid_client with ${tokenAuthMethod}; retrying once with ${fallbackMethod}`);

                    const fallbackBody = new URLSearchParams();
                    fallbackBody.append('grant_type', params.grant_type || 'authorization_code');
                    fallbackBody.append('code', params.code);
                    fallbackBody.append('redirect_uri', params.redirect_uri);
                    fallbackBody.append('client_id', params.client_id);

                    const fallbackHeaders = {
                        'Content-Type': 'application/x-www-form-urlencoded'
                    };

                    if (fallbackMethod === 'client_secret_post') {
                        fallbackBody.append('client_secret', params.client_secret);
                    } else {
                        const basic = this.toBase64(`${params.client_id}:${params.client_secret}`);
                        fallbackHeaders['Authorization'] = `Basic ${basic}`;
                    }

                    if (params.code_verifier) {
                        fallbackBody.append('code_verifier', params.code_verifier);
                    }

                    response = await this.executeTokenRequest(tokenUrl, fallbackBody.toString(), fallbackHeaders);
                    console.log('Fallback response status:', response.status);

                    if (response.ok) {
                        console.log(`✓ Fallback token auth succeeded with ${fallbackMethod}`);
                        const tokenData = await response.json();
                        console.log('Token response:', {
                            ...tokenData,
                            access_token: tokenData.access_token ? tokenData.access_token.substring(0, 20) + '...' : 'N/A'
                        });
                        return tokenData;
                    }

                    const fallbackText = await response.text();
                    console.error('Fallback token exchange failed:', {
                        status: response.status,
                        statusText: response.statusText,
                        body: fallbackText,
                        attemptedMethod: fallbackMethod
                    });
                    throw new Error(
                        `Token exchange failed: ${response.status} - ${fallbackText || 'invalid_client'} (tried ${tokenAuthMethod} then ${fallbackMethod})`
                    );
                }

                throw new Error(`Token exchange failed: ${response.status} - ${errorData.error_description || errorData.error || errorText}`);
            }

            const tokenData = await response.json();
            console.log('✓ Token exchange successful');
            console.log('Token response:', {
                ...tokenData,
                access_token: tokenData.access_token ? tokenData.access_token.substring(0, 20) + '...' : 'N/A'
            });

            return tokenData;

        } catch (error) {
            console.error('Token exchange error:', error);
            throw error;
        }
    },

    /**
     * Check if a server needs custom token handling
     */
    needsCustomHandling(serverKey) {
        // List of servers that need custom token exchange
        const customServers = ['cigna', 'anthem'];
        return customServers.includes(serverKey);
    }
};

// Make it globally available
window.TokenHandler = TokenHandler;
