// Code Generated by Sidekick is for learning and experimentation purposes only.
// Configuration for GitHub Pages Deployment
// IMPORTANT: No trailing slashes on base URLs
const GITHUB_PAGES_URL = "https://russellott.github.io/fhirapps/PatientAccess";
const GITHUB_ORIGIN = "https://russellott.github.io";  // Origin header will be just the domain

const FHIR_SERVERS = {

    // HealthInteractive public test server
    deloitte: {
        name: "Deloitte HealthInteractive Server",
        clientId: "sharedClient2",
        clientSecret: "CJoSQwBfBmweH8WzEqpEGa10HkCEIOr6",
        usePkce: false,
        tokenAuthMethod: "client_secret_post",
        tokenReferrerPolicy: "origin",
        allowBasicAuthFallback: false,
        scope: "patient/*.read launch/patient offline_access",
        // CRITICAL: These must EXACTLY match what's registered in Cigna Developer Portal
        redirectUri: `${GITHUB_PAGES_URL}/app.html`,  // https://russellott.github.io/demosmartapp/app.html
        launchUri: `${GITHUB_PAGES_URL}/launch.html`,  // https://russellott.github.io/demosmartapp/launch.html
        iss: "https://deloitte.connectathons.com/",
        authorizeUrl: "https://deloitte.connectathons.com/auth",
        tokenUrl: "https://deloitte.connectathons.com/token",
        description: "Deloitte connectathon sandbox server with sample patients (R4)",
        requiresStateNonce: true,
        useNumericStateNonce: true,
        // Expected Origin header (browser will send this automatically)
        expectedOrigin: GITHUB_ORIGIN  // https://russellott.github.io
    },
    
    // SMART Health IT Sandbox - Public Testing Sandbox (No Registration Required)
    sandbox: {
        name: "SMART Health IT Sandbox",
        clientId: "demo_app_whatever",
        clientSecret: null,
        usePkce: true,
        scope: "launch/patient patient/*.read openid fhirUser offline_access",
        redirectUri: `${GITHUB_PAGES_URL}/app.html`,  // https://russellott.github.io/demosmartapp/app.html
        launchUri: `${GITHUB_PAGES_URL}/launch.html`,
        iss: "https://launch.smarthealthit.org/v/r4/sim/WzMsIiIsIiIsIkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMSwiIl0/fhir",
        authorizeUrl: "https://launch.smarthealthit.org/v/r4/sim/WzMsIiIsIiIsIkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMSwiIl0/auth/authorize",
        tokenUrl: "https://launch.smarthealthit.org/v/r4/sim/WzMsIiIsIiIsIkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMSwiIl0/auth/token",
        description: "Public testing sandbox with sample patients (R4, AUTO simulation)",
        isPublic: true
    },

    // Cigna FHIR Server
    cigna: {
        name: "Cigna Developer API",
        clientId: "5f965408-7972-4813-b25a-288d7169031c",
        clientSecret: null,
        usePkce: true,
        tokenAuthMethod: "client_secret_post",
        tokenReferrerPolicy: "origin",
        allowBasicAuthFallback: false,
        scope: "patient/*.read launch/patient openid fhirUser offline_access",
        // CRITICAL: These must EXACTLY match what's registered in Cigna Developer Portal
        redirectUri: `${GITHUB_PAGES_URL}/app.html`,  // https://russellott.github.io/demosmartapp/app.html
        launchUri: `${GITHUB_PAGES_URL}/launch.html`,  // https://russellott.github.io/demosmartapp/launch.html
        iss: "https://fhir.cigna.com/PatientAccess/v1-devportal",
        authorizeUrl: "https://r-hi2.cigna.com/mga/sps/oauth/oauth20/authorize",
        tokenUrl: "https://r-hi2.cigna.com/mga/sps/oauth/oauth20/token",
        description: "Real payer FHIR API for CMS Patient Access",
        requiresStateNonce: true,
        useNumericStateNonce: true,
        // Expected Origin header (browser will send this automatically)
        expectedOrigin: GITHUB_ORIGIN  // https://russellott.github.io
    },

    // EPIC Sandbox FHIR Server
    epic: {
        name: "Epic Sandbox FHIR API",
        clientId: "ada7f357-1f77-4b67-ba77-ea676f089243",
        clientSecret: "hrKQtSvnsvCfMzv8WBlQA1rULhF5X4Tq5wxyUMfMUrOYQtdxKsIEqF0LVZI7tVZRuvBTKSkPBpHnMCDyMUsc5g==",
        usePkce: true,
        tokenAuthMethod: "none",
        scope: "patient/*.read launch/patient openid fhirUser offline_access",
        redirectUri: `${GITHUB_PAGES_URL}/app.html`,
        launchUri: `${GITHUB_PAGES_URL}/launch.html`,
        iss: "https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/R4",
        authorizeUrl: "https://fhir.epic.com/interconnect-fhir-oauth/oauth2/authorize",
        tokenUrl: "https://fhir.epic.com/interconnect-fhir-oauth/oauth2/token",
        description: "Real payer FHIR API for CMS Patient Access",
        requiresStateNonce: true,
        useNumericStateNonce: true,
        // Expected Origin header (browser will send this automatically)
        description: "Epic's CMS-compliant Patient Access API",
        expectedOrigin: GITHUB_ORIGIN
    },

    // Logica Health Sandbox
    logica: {
        name: "Logica Health Sandbox",
        clientId: "demo_app_logica",
        clientSecret: null,
        usePkce: true,
        scope: "launch/patient patient/*.read openid fhirUser offline_access",
        redirectUri: `${GITHUB_PAGES_URL}/app.html`,
        launchUri: `${GITHUB_PAGES_URL}/launch.html`,
        iss: "https://api.logicahealth.org/FHIRResearchSandbox/open/",
        description: "Advanced testing sandbox with rich test data",
        isPublic: true,
        expectedOrigin: GITHUB_ORIGIN
    }
};

// Set which server to use by default
const ACTIVE_SERVER = 'cigna';

// Helper function to generate numeric state/nonce
function generateNumericToken(length = 10) {
    let result = '';
    for (let i = 0; i < length; i++) {
        result += Math.floor(Math.random() * 10);
    }
    return result;
}

// Helper function to get current configuration
function getCurrentConfig() {
    return FHIR_SERVERS[ACTIVE_SERVER];
}

// Helper to check if server is configured
function isServerConfigured(serverKey) {
    const server = FHIR_SERVERS[serverKey];
    if (!server || !server.clientId) return false;

    // Public sandboxes are always "configured"
    if (server.isPublic) {
        return true;
    }

    // For private/production servers, check if they have real credentials
    const placeholders = [
        'YOUR_CLIENT_ID',
        'YOUR_' + serverKey.toUpperCase() + '_CLIENT_ID',
        'YOUR_SANDBOX_CLIENT_ID',
        'YOUR_ANTHEM_CLIENT_ID',
        'YOUR_LOGICA_CLIENT_ID'
    ];

    return !placeholders.some(p => server.clientId.includes(p));
}

// Log configuration on load
console.log('=== App Configuration ===');
console.log('GitHub Pages URL:', GITHUB_PAGES_URL);
console.log('Expected Origin:', GITHUB_ORIGIN);
console.log('Active Server:', ACTIVE_SERVER);
console.log('Server Config:', {
    ...FHIR_SERVERS[ACTIVE_SERVER],
    clientSecret: FHIR_SERVERS[ACTIVE_SERVER]?.clientSecret ? '***HIDDEN***' : 'not provided'
});
