// Code Generated by Sidekick is for learning and experimentation purposes only.
// Provider Directory Browser Configuration
// IMPORTANT: No trailing slashes on base URLs
const GITHUB_PAGES_URL = "https://russellott.github.io/demosmartapp/ProviderDirectoryBrowser";
const GITHUB_ORIGIN = "https://russellott.github.io";

const PROVIDER_DIRECTORIES = {
    // SMART Health IT Sandbox Provider Directory (public, no auth required)
    smart_sandbox: {
        name: "SMART Health IT Sandbox",
        baseUrl: "https://launch.smarthealthit.org/v/r4/sim/WzMsIiIsIiIsIkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMSwiIl0/fhir",
        description: "Public testing sandbox with sample provider data (R4, AUTO simulation)",
        searchResources: true,
        supportedResources: ["Practitioner", "Organization", "Location", "PractitionerRole"],
        isPublic: true
    },

    // California Mental Health Services Authority Provider Directory (public, no auth required)
    calmhsa: {
        name: "California Mental Health Services Authority",
        baseUrl: "https://fhir-calmhsa-provider.ehn-prod.net/fhir",
        description: "Production Provider Directory for California Mental Health Services Authority (CalMHSA)",
        searchResources: true,
        supportedResources: ["Practitioner", "Organization", "Location", "PractitionerRole", "HealthcareService"],
        isPublic: true
    },

    // Washington State Health Care Authority Provider Directory (public, no auth required)
    wshca: {
        name: "Washington State Health Care Authority",
        baseUrl: "https://wa.fhir.mhbapp.com/pd/api/v1",
        description: "Washington State Health Care Authority - ProviderOne Directory",
        searchResources: true,
        supportedResources: ["Practitioner", "Organization", "Location", "PractitionerRole"],
        isPublic: true
    }
};

// Set which directory to use by default
const ACTIVE_DIRECTORY = 'smart_sandbox';

// Helper function to get current configuration
function getCurrentDirectoryConfig() {
    return PROVIDER_DIRECTORIES[ACTIVE_DIRECTORY];
}

// Helper to check if directory is accessible
function isDirectoryAccessible(directoryKey) {
    const directory = PROVIDER_DIRECTORIES[directoryKey];
    if (!directory || !directory.baseUrl) return false;
    return directory.isPublic === true;
}

// Log configuration on load
console.log('=== Provider Directory Browser Configuration ===');
console.log('GitHub Pages URL:', GITHUB_PAGES_URL);
console.log('Expected Origin:', GITHUB_ORIGIN);
console.log('Active Directory:', ACTIVE_DIRECTORY);
console.log('Directory Config:', PROVIDER_DIRECTORIES[ACTIVE_DIRECTORY]);
