// Code Generated by Sidekick is for learning and experimentation purposes only.
// Provider Directory Browser Configuration
// IMPORTANT: No trailing slashes on base URLs
const GITHUB_PAGES_URL = "https://russellott.github.io/demosmartapp/ProviderDirectoryBrowser";
const GITHUB_ORIGIN = "https://russellott.github.io";

const PROVIDER_DIRECTORIES = {
    // SMART Health IT Sandbox Provider Directory (public, no auth required)
    smart_sandbox: {
        name: "SMART Health IT Sandbox",
        baseUrl: "https://launch.smarthealthit.org/v/r4/sim/WzMsIiIsIiIsIkFVVE8iLDAsMCwwLCIiLCIiLCIiLCIiLCIiLCIiLCIiLDAsMSwiIl0/fhir",
        description: "Public testing sandbox with sample provider data (R4, AUTO simulation)",
        searchResources: true,
        supportedResources: ["Practitioner", "Organization", "Location", "PractitionerRole"],
        isPublic: true
    },

    // Logica Health Open Sandbox Provider Directory
    logica_open: {
        name: "Logica Health Open Sandbox",
        baseUrl: "https://api.logicahealth.org/FHIRResearchSandbox/open/fhir",
        description: "Advanced testing sandbox with comprehensive provider directory data",
        searchResources: true,
        supportedResources: ["Practitioner", "Organization", "Location", "PractitionerRole", "HealthcareService"],
        isPublic: true
    },

    // FHIR Test Server (public, generic FHIR server)
    fhir_test: {
        name: "FHIR Test Server (Hapi)",
        baseUrl: "http://hapi.fhir.org/baseR4",
        description: "Public HAPI FHIR test server with provider directory resources",
        searchResources: true,
        supportedResources: ["Practitioner", "Organization", "Location", "PractitionerRole"],
        isPublic: true
    }
};

// Set which directory to use by default
const ACTIVE_DIRECTORY = 'smart_sandbox';

// Helper function to get current configuration
function getCurrentDirectoryConfig() {
    return PROVIDER_DIRECTORIES[ACTIVE_DIRECTORY];
}

// Helper to check if directory is accessible
function isDirectoryAccessible(directoryKey) {
    const directory = PROVIDER_DIRECTORIES[directoryKey];
    if (!directory || !directory.baseUrl) return false;
    return directory.isPublic === true;
}

// Log configuration on load
console.log('=== Provider Directory Browser Configuration ===');
console.log('GitHub Pages URL:', GITHUB_PAGES_URL);
console.log('Expected Origin:', GITHUB_ORIGIN);
console.log('Active Directory:', ACTIVE_DIRECTORY);
console.log('Directory Config:', PROVIDER_DIRECTORIES[ACTIVE_DIRECTORY]);
